package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Jelo generated by hbm2java
 */
@Entity
@Table(name = "jelo", catalog = "si2015tim5", uniqueConstraints = @UniqueConstraint(columnNames = "naziv"))
public class Jelo implements java.io.Serializable {

	private Integer id;
	private String opis;
	private String naziv;
	private double cijena;
	private Set<SastojciJeloVeza> sastojciJeloVezas = new HashSet<SastojciJeloVeza>(0);
	private Set<NarudzbaJeloVeza> narudzbajelovezas = new HashSet<NarudzbaJeloVeza>(0);

	public Jelo() {
	}

	public Jelo(String naziv, double cijena) {
		this.naziv = naziv;
		this.cijena = cijena;
	}

	public Jelo(String naziv, double cijena, Set<SastojciJeloVeza> sastojciJeloVezas,
			Set<NarudzbaJeloVeza> narudzbajelovezas) {
		this.naziv = naziv;
		this.cijena = cijena;
		this.sastojciJeloVezas = sastojciJeloVezas;
		this.narudzbajelovezas = narudzbajelovezas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naziv", unique = true, nullable = false, length = 50)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "cijena", nullable = false, precision = 22, scale = 0)
	public double getCijena() {
		return this.cijena;
	}

	public void setCijena(double cijena) {
		this.cijena = cijena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jelo")
	public Set<SastojciJeloVeza> getSastojciJeloVezas() {
		return this.sastojciJeloVezas;
	}

	public void setSastojciJeloVezas(Set<SastojciJeloVeza> sastojciJeloVezas) {
		this.sastojciJeloVezas = sastojciJeloVezas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jelo")
	public Set<NarudzbaJeloVeza> getNarudzbajelovezas() {
		return this.narudzbajelovezas;
	}

	public void setNarudzbajelovezas(Set<NarudzbaJeloVeza> narudzbajelovezas) {
		this.narudzbajelovezas = narudzbajelovezas;
	}

	public void setOpis(String opis) {
		this.opis=opis;
		// TODO Auto-generated method stub
		
	}

}
