package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kupac generated by hbm2java
 */
@Entity
@Table(name = "kupac", catalog = "si2015tim5")
public class Kupac implements java.io.Serializable {

	private int id;
	private String adresa;
	private Integer brojTelefona;
	private String info;
	private Set<Narudzba> narudzbas = new HashSet<Narudzba>(0);

	public Kupac() {
	}

	public Kupac(int id) {
		this.id = id;
	}

	public Kupac(int id, String adresa, Integer brojTelefona, String info, Set<Narudzba> narudzbas) {
		this.id = id;
		this.adresa = adresa;
		this.brojTelefona = brojTelefona;
		this.info = info;
		this.narudzbas = narudzbas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "adresa", length = 50)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "brojTelefona")
	public Integer getBrojTelefona() {
		return this.brojTelefona;
	}

	public void setBrojTelefona(Integer brojTelefona) {
		this.brojTelefona = brojTelefona;
	}

	@Column(name = "info", length = 200)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kupac")
	public Set<Narudzba> getNarudzbas() {
		return this.narudzbas;
	}

	public void setNarudzbas(Set<Narudzba> narudzbas) {
		this.narudzbas = narudzbas;
	}

}
