package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Narudzbajeloveza generated by hbm2java
 */
@Entity
@Table(name = "narudzbajeloveza", catalog = "tim5")
public class NarudzbaJeloVeza implements java.io.Serializable {

	private int id;
	private Jelo jelo;
	private Narudzba narudzba;
	private int kolicina;

	public NarudzbaJeloVeza() {
	}

	public NarudzbaJeloVeza(int id, Jelo jelo, Narudzba narudzba, int kolicina) {
		this.id = id;
		this.jelo = jelo;
		this.narudzba = narudzba;
		this.kolicina = kolicina;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JeloId", nullable = false)
	public Jelo getJelo() {
		return this.jelo;
	}

	public void setJelo(Jelo jelo) {
		this.jelo = jelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NarudzbaId", nullable = false)
	public Narudzba getNarudzba() {
		return this.narudzba;
	}

	public void setNarudzba(Narudzba narudzba) {
		this.narudzba = narudzba;
	}

	@Column(name = "kolicina", nullable = false)
	public int getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(int kolicina) {
		this.kolicina = kolicina;
	}

}
