package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Narudzba generated by hbm2java
 */
@Entity
@Table(name = "narudzba", catalog = "tim5")
public class Narudzba implements java.io.Serializable {

	private Integer id;
	private Kupac kupac;
	private Zaposlenik zaposlenikByZaposlenikOsobaIdDostavljac;
	private Zaposlenik zaposlenikByZaposlenikOsobaIdKuhar;
	private Zaposlenik zaposlenikByZaposlenikOsobaIdPrimalac;
	private double cijena;
	private int status;
	private Date vrijemePrijema;
	private Date vrijemePocetkaPripreme;
	private Date vrijemePreuzimanja;
	private Date vrijemeDostave;
	private double novacaDostavljeno;
	private String opis;
	private Set<NarudzbaJeloVeza> narudzbajelovezas = new HashSet<NarudzbaJeloVeza>(0);

	public Narudzba() {
	}

	public Narudzba(Kupac kupac, Zaposlenik zaposlenikByZaposlenikOsobaIdPrimalac, double cijena, int status,
			Date vrijemePrijema, double novacaDostavljeno) {
		this.kupac = kupac;
		this.zaposlenikByZaposlenikOsobaIdPrimalac = zaposlenikByZaposlenikOsobaIdPrimalac;
		this.cijena = cijena;
		this.status = status;
		this.vrijemePrijema = vrijemePrijema;
		this.novacaDostavljeno = novacaDostavljeno;
	}

	public Narudzba(Kupac kupac, Zaposlenik zaposlenikByZaposlenikOsobaIdDostavljac,
			Zaposlenik zaposlenikByZaposlenikOsobaIdKuhar, Zaposlenik zaposlenikByZaposlenikOsobaIdPrimalac,
			double cijena, int status, Date vrijemePrijema, Date vrijemePocetkaPripreme, Date vrijemePreuzimanja,
			Date vrijemeDostave, double novacaDostavljeno, String opis, Set<NarudzbaJeloVeza> narudzbajelovezas) {
		this.kupac = kupac;
		this.zaposlenikByZaposlenikOsobaIdDostavljac = zaposlenikByZaposlenikOsobaIdDostavljac;
		this.zaposlenikByZaposlenikOsobaIdKuhar = zaposlenikByZaposlenikOsobaIdKuhar;
		this.zaposlenikByZaposlenikOsobaIdPrimalac = zaposlenikByZaposlenikOsobaIdPrimalac;
		this.cijena = cijena;
		this.status = status;
		this.vrijemePrijema = vrijemePrijema;
		this.vrijemePocetkaPripreme = vrijemePocetkaPripreme;
		this.vrijemePreuzimanja = vrijemePreuzimanja;
		this.vrijemeDostave = vrijemeDostave;
		this.novacaDostavljeno = novacaDostavljeno;
		this.opis = opis;
		this.narudzbajelovezas = narudzbajelovezas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KupacOsobaId", nullable = false)
	public Kupac getKupac() {
		return this.kupac;
	}

	public void setKupac(Kupac kupac) {
		this.kupac = kupac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZaposlenikOsobaId_Dostavljac")
	public Zaposlenik getZaposlenikByZaposlenikOsobaIdDostavljac() {
		return this.zaposlenikByZaposlenikOsobaIdDostavljac;
	}

	public void setZaposlenikByZaposlenikOsobaIdDostavljac(Zaposlenik zaposlenikByZaposlenikOsobaIdDostavljac) {
		this.zaposlenikByZaposlenikOsobaIdDostavljac = zaposlenikByZaposlenikOsobaIdDostavljac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZaposlenikOsobaId_Kuhar")
	public Zaposlenik getZaposlenikByZaposlenikOsobaIdKuhar() {
		return this.zaposlenikByZaposlenikOsobaIdKuhar;
	}

	public void setZaposlenikByZaposlenikOsobaIdKuhar(Zaposlenik zaposlenikByZaposlenikOsobaIdKuhar) {
		this.zaposlenikByZaposlenikOsobaIdKuhar = zaposlenikByZaposlenikOsobaIdKuhar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZaposlenikOsobaId_Primalac", nullable = false)
	public Zaposlenik getZaposlenikByZaposlenikOsobaIdPrimalac() {
		return this.zaposlenikByZaposlenikOsobaIdPrimalac;
	}

	public void setZaposlenikByZaposlenikOsobaIdPrimalac(Zaposlenik zaposlenikByZaposlenikOsobaIdPrimalac) {
		this.zaposlenikByZaposlenikOsobaIdPrimalac = zaposlenikByZaposlenikOsobaIdPrimalac;
	}

	@Column(name = "cijena", nullable = false, precision = 22, scale = 0)
	public double getCijena() {
		return this.cijena;
	}

	public void setCijena(double cijena) {
		this.cijena = cijena;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vrijemePrijema", nullable = false, length = 19)
	public Date getVrijemePrijema() {
		return this.vrijemePrijema;
	}

	public void setVrijemePrijema(Date vrijemePrijema) {
		this.vrijemePrijema = vrijemePrijema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vrijemePocetkaPripreme", length = 19)
	public Date getVrijemePocetkaPripreme() {
		return this.vrijemePocetkaPripreme;
	}

	public void setVrijemePocetkaPripreme(Date vrijemePocetkaPripreme) {
		this.vrijemePocetkaPripreme = vrijemePocetkaPripreme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vrijemePreuzimanja", length = 19)
	public Date getVrijemePreuzimanja() {
		return this.vrijemePreuzimanja;
	}

	public void setVrijemePreuzimanja(Date vrijemePreuzimanja) {
		this.vrijemePreuzimanja = vrijemePreuzimanja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vrijemeDostave", length = 19)
	public Date getVrijemeDostave() {
		return this.vrijemeDostave;
	}

	public void setVrijemeDostave(Date vrijemeDostave) {
		this.vrijemeDostave = vrijemeDostave;
	}

	@Column(name = "novacaDostavljeno", nullable = false, precision = 22, scale = 0)
	public double getNovacaDostavljeno() {
		return this.novacaDostavljeno;
	}

	public void setNovacaDostavljeno(double novacaDostavljeno) {
		this.novacaDostavljeno = novacaDostavljeno;
	}

	@Column(name = "opis", length = 200)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "narudzba")
	public Set<NarudzbaJeloVeza> getNarudzbajelovezas() {
		return this.narudzbajelovezas;
	}

	public void setNarudzbajelovezas(Set<NarudzbaJeloVeza> narudzbajelovezas) {
		this.narudzbajelovezas = narudzbajelovezas;
	}

}
