package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Radnomjesto generated by hbm2java
 */
@Entity
@Table(name = "radnomjesto", catalog = "si2015tim5")
public class RadnoMjesto implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String opis;
	private Set<Zaposlenik> zaposleniks = new HashSet<Zaposlenik>(0);

	public RadnoMjesto() {
	}

	public RadnoMjesto(String naziv) {
		this.naziv = naziv;
	}

	public RadnoMjesto(String naziv, String opis, Set<Zaposlenik> zaposleniks) {
		this.naziv = naziv;
		this.opis = opis;
		this.zaposleniks = zaposleniks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naziv", nullable = false, length = 50)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "opis", length = 500)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "radnomjesto")
	public Set<Zaposlenik> getZaposleniks() {
		return this.zaposleniks;
	}

	public void setZaposleniks(Set<Zaposlenik> zaposleniks) {
		this.zaposleniks = zaposleniks;
	}

}
