package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sastojak generated by hbm2java
 */
@Entity
@Table(name = "sastojak", catalog = "si2015tim5", uniqueConstraints = @UniqueConstraint(columnNames = "naziv"))
public class Sastojak implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String opis;
	private String mjernaJedinica;
	private Set<SastojciJeloVeza> sastojciJeloVezas = new HashSet<SastojciJeloVeza>(0);
	private boolean izbrisan;
	public Sastojak() {
	}

	public Sastojak(String naziv, String mjernaJedinica) {
		this.izbrisan=false;
		this.naziv = naziv;
		this.mjernaJedinica = mjernaJedinica;
	}

	public Sastojak(String naziv, String opis, String mjernaJedinica, Set<SastojciJeloVeza> sastojciJeloVezas) {
		this.izbrisan=false;
		this.naziv = naziv;
		this.opis = opis;
		this.mjernaJedinica = mjernaJedinica;
		this.sastojciJeloVezas = sastojciJeloVezas;
	}
	@Column(name = "izbrisan", unique = false)
	public boolean isIzbrisan() {
		return izbrisan;
	}

	public void setIzbrisan(boolean izbrisan) {
		this.izbrisan = izbrisan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naziv", unique = true, nullable = false, length = 50)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "opis", length = 500)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@Column(name = "mjernaJedinica", nullable = false, length = 10)
	public String getMjernaJedinica() {
		return this.mjernaJedinica;
	}

	public void setMjernaJedinica(String mjernaJedinica) {
		this.mjernaJedinica = mjernaJedinica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sastojak")
	public Set<SastojciJeloVeza> getSastojciJeloVezas() {
		return this.sastojciJeloVezas;
	}

	public void setSastojciJeloVezas(Set<SastojciJeloVeza> sastojciJeloVezas) {
		this.sastojciJeloVezas = sastojciJeloVezas;
	}

}
