package ba.unsa.etf.si.TelefonskeNarudzbe.DomainModels;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 12-May-2016 01:37:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zaposlenik generated by hbm2java
 */
@Entity

@Table(name = "zaposlenik", catalog = "si2015tim5")
public class Zaposlenik implements java.io.Serializable {

	private int id;
	private RadnoMjesto radnomjesto;
	private String username;
	private String password;
	private String datumRodenja;
	private String imePrezime;
	private String dodatneInformacije;
	private Set<Narudzba> narudzbasForZaposlenikOsobaIdDostavljac = new HashSet<Narudzba>(0);
	private Set<Narudzba> narudzbasForZaposlenikOsobaIdKuhar = new HashSet<Narudzba>(0);
	private Set<Narudzba> narudzbasForZaposlenikOsobaIdPrimalac = new HashSet<Narudzba>(0);
	

	public Zaposlenik() {
	}

	public Zaposlenik(int id, RadnoMjesto radnomjesto, String username, String password) {
		this.id = id;
		this.radnomjesto = radnomjesto;
		this.username = username;
		this.password = password;
	}

	public Zaposlenik(int id, RadnoMjesto radnomjesto, String username, String password, String datumRodenja,
			Set<Narudzba> narudzbasForZaposlenikOsobaIdDostavljac, Set<Narudzba> narudzbasForZaposlenikOsobaIdKuhar,
			Set<Narudzba> narudzbasForZaposlenikOsobaIdPrimalac) {
		this.id = id;
		this.radnomjesto = radnomjesto;
		this.username = username;
		this.password = password;
		this.datumRodenja = datumRodenja;
		this.narudzbasForZaposlenikOsobaIdDostavljac = narudzbasForZaposlenikOsobaIdDostavljac;
		this.narudzbasForZaposlenikOsobaIdKuhar = narudzbasForZaposlenikOsobaIdKuhar;
		this.narudzbasForZaposlenikOsobaIdPrimalac = narudzbasForZaposlenikOsobaIdPrimalac;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "radnoMjesto", nullable = false)
	public RadnoMjesto getRadnomjesto() {
		return this.radnomjesto;
	}

	public void setRadnomjesto(RadnoMjesto radnomjesto) {
		this.radnomjesto = radnomjesto;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "datumRodenja", length = 50)
	public String getDatumRodenja() {
		return this.datumRodenja;
	}

	public void setDatumRodenja(String datumRodenja) {
		this.datumRodenja = datumRodenja;
	}

	@Column(name = "dodatneInformacije", unique = false, nullable = true, length=500)
	public String getDodatneInformacije() {
		return dodatneInformacije;
	}

	public void setDodatneInformacije(String dodatneInformacije) {
		this.dodatneInformacije = dodatneInformacije;
	}
	
	
	@Column(name = "imePrezime", unique = false, nullable = true, length=20)
	public String getImePrezime() {
		return imePrezime;
	}

	public void setImePrezime(String imePrezime) {
		this.imePrezime = imePrezime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zaposlenikByZaposlenikOsobaIdDostavljac")
	public Set<Narudzba> getNarudzbasForZaposlenikOsobaIdDostavljac() {
		return this.narudzbasForZaposlenikOsobaIdDostavljac;
	}

	public void setNarudzbasForZaposlenikOsobaIdDostavljac(Set<Narudzba> narudzbasForZaposlenikOsobaIdDostavljac) {
		this.narudzbasForZaposlenikOsobaIdDostavljac = narudzbasForZaposlenikOsobaIdDostavljac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zaposlenikByZaposlenikOsobaIdKuhar")
	public Set<Narudzba> getNarudzbasForZaposlenikOsobaIdKuhar() {
		return this.narudzbasForZaposlenikOsobaIdKuhar;
	}

	public void setNarudzbasForZaposlenikOsobaIdKuhar(Set<Narudzba> narudzbasForZaposlenikOsobaIdKuhar) {
		this.narudzbasForZaposlenikOsobaIdKuhar = narudzbasForZaposlenikOsobaIdKuhar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zaposlenikByZaposlenikOsobaIdPrimalac")
	public Set<Narudzba> getNarudzbasForZaposlenikOsobaIdPrimalac() {
		return this.narudzbasForZaposlenikOsobaIdPrimalac;
	}

	public void setNarudzbasForZaposlenikOsobaIdPrimalac(Set<Narudzba> narudzbasForZaposlenikOsobaIdPrimalac) {
		this.narudzbasForZaposlenikOsobaIdPrimalac = narudzbasForZaposlenikOsobaIdPrimalac;
	}

	
}
